

export const data = [
    { id: 1, location: "Abbey Road", CRS: "ZAL" },
    { id: 2, location: "Abbey Wood", CRS: "ABW" },
    { id: 3, location: "Abercwmboi", CRS: "ABI" },
    { id: 4, location: "Abercynon", CRS: "ACY" },
    { id: 5, location: "Aberdour", CRS: "AUR" },
    { id: 7, location: "Abbey Wood Crossrail", CRS: "ABX" },
    { id: 8, location: "Abbotswood Junction", CRS: "AWJ" },
    { id: 9, location: "Aber", CRS: "ABE" },
    { id: 10, location: "Abercynon North", CRS: "ABR" },
    { id: 11, location: "Aberdare", CRS: "ABA" },
    { id: 12, location: "Aberdare Penywaun", CRS: "XPZ" },
    { id: 13, location: "Aberdare Trecynon", CRS: "XTO" },
    { id: 14, location: "Aberdeen", CRS: "ABD" },
    { id: 15, location: "Aberdeen Clayhills Carriage Maintenance Depot", CRS: "XAC" },
    { id: 16, location: "Aberdovey", CRS: "AVY" },
    { id: 17, location: "Abererch", CRS: "ABH" },
    { id: 18, location: "Aberffrwd", CRS: "AFD" },
    { id: 19, location: "Abergavenny", CRS: "AGV" },
    { id: 20, location: "Abergele & Pensarn", CRS: "AGL" },
    { id: 21, location: "Aberpergwm", CRS: "APW" },
    { id: 22, location: "Aberthaw Cement Works", CRS: "AWC" },
    { id: 23, location: "Aberthaw National Power Oil Siding", CRS: "AWN" },
    { id: 24, location: "Aberthaw Reception Sidings", CRS: "ARS" },
    { id: 25, location: "Aberystwyth", CRS: "AYW" },
    { id: 26, location: "Aberystwyth Dole Level Crossing", CRS: "DOE" },
    { id: 27, location: "Abraham Moss", CRS: "AHM" },
    { id: 28, location: "Abingdon High Street", CRS: "XAE" },
    { id: 29, location: "Aboyne (Main Street)", CRS: "ABO" },
    { id: 30, location: "Accrington", CRS: "ACR" },
    { id: 31, location: "Achanalt", CRS: "AAT" },
    { id: 32, location: "Achnasheen", CRS: "ACN" },
    { id: 33, location: "Achnashellach", CRS: "ACH" },
    { id: 34, location: "Acklington", CRS: "ACK" },
    { id: 35, location: "Acle", CRS: "ACL" },
    { id: 36, location: "Acocks Green", CRS: "ACG" },
    { id: 37, location: "Acton Bridge", CRS: "ACB" },
    { id: 38, location: "Acton Central", CRS: "ACC" },
    { id: 39, location: "Acton Main Line", CRS: "AML" },
    { id: 40, location: "Acton Terminal Complex", CRS: "XAX" },
    { id: 41, location: "Acton Town LT", CRS: "ZAT" },
    { id: 42, location: "Adderley Park", CRS: "ADD" },
    { id: 43, location: "Addiewell", CRS: "ADW" },
    { id: 44, location: "Addiscombe", CRS: "ACM" },
    { id: 45, location: "Addlestone", CRS: "ASN" },
    { id: 46, location: "Adisham", CRS: "ADM" },
    { id: 47, location: "Adlington (Cheshire)", CRS: "ADC" },
    { id: 48, location: "Adlington (Lancashire)", CRS: "ADL" },
    { id: 49, location: "Adwick", CRS: "AWK" },
    { id: 50, location: "Aigburth", CRS: "AIG" },
    { id: 51, location: "Ainsdale", CRS: "ANS" },
    { id: 52, location: "Aintree", CRS: "AIN" },
    { id: 53, location: "Airbles", CRS: "AIR" },
    { id: 54, location: "Airdrie", CRS: "ADR" },
    { id: 55, location: "Airport Tyne & Wear Metro", CRS: "APN" },
    { id: 56, location: "Akeman Street UK Fertilizers", CRS: "AKS" },
    { id: 57, location: "Albany Park", CRS: "AYP" },
    { id: 58, location: "Albrighton", CRS: "ALB" },
    { id: 59, location: "Alderley Edge", CRS: "ALD" },
    { id: 60, location: "Aldermaston", CRS: "AMT" },
    { id: 61, location: "Aldersbrook Up Carriage Holding Sidings", CRS: "XAK" },
    { id: 62, location: "Aldershot", CRS: "AHT" },
    { id: 63, location: "Aldgate", CRS: "ZAD" },
    { id: 64, location: "Aldgate East", CRS: "ZAE" },
    { id: 65, location: "Aldrington", CRS: "AGT" },
    { id: 66, location: "Alexandra Palace", CRS: "AAP" },
    { id: 67, location: "Alexandra Parade", CRS: "AXP" },
    { id: 68, location: "Alexandria", CRS: "ALX" },
    { id: 69, location: "Alfreton & Mansfield Parkway", CRS: "ALF" },
    { id: 70, location: "Alfreton East Midlands Designer Outlet Village", CRS: "XYX" },
    { id: 71, location: "Allens West", CRS: "ALW" },
    { id: 72, location: "Allerton", CRS: "ALE" },
    { id: 73, location: "Allerton Diesel Multiple Unit Depot", CRS: "XAL	" },
    { id: 74, location: "Allington ARC Siding", CRS: "ALA" },
    { id: 75, location: "Alloa", CRS: "ALO" },
    { id: 76, location: "Alloa Bus Link", CRS: "ABL" },
    { id: 77, location: "All Saints DLR", CRS: "ZAS" },
    { id: 78, location: "Alness", CRS: "ASS" },
    { id: 79, location: "Alnmouth", CRS: "ALM" },
    { id: 80, location: "Alperton LT", CRS: "ZAP" },
    { id: 81, location: "Alresford (Essex)", CRS: "ALR" },
    { id: 82, location: "Alsager", CRS: "ASG" },
    { id: 83, location: "Alstone Carriage Holding Sidings", CRS: "XCX" },
    { id: 84, location: "Alston (Townhead)", CRS: "ALS" },
    { id: 85, location: "Althorne", CRS: "ALN" },
    { id: 86, location: "Althorpe", CRS: "ALP" },
    { id: 87, location: "Altnabreac", CRS: "ABC" },
    { id: 88, location: "Altofts", CRS: "ATS" },
    { id: 89, location: "Alton", CRS: "AON" },
    { id: 90, location: "Alton Towers", CRS: "ATW" },
    { id: 91, location: "Altrincham", CRS: "ALT" },
    { id: 92, location: "Altrincham For Old Trafford", CRS: "ALZ" },
    { id: 93, location: "Altrincham Metrolink", CRS: "XNA" },
    { id: 94, location: "Alvechurch", CRS: "ALV" },
    { id: 95, location: "Ambergate", CRS: "AMB" },
    { id: 96, location: "Ambergate Junction", CRS: "XAJ" },
    { id: 97, location: "Amberley", CRS: "AMY" },
    { id: 98, location: "Amersham", CRS: "AMR" },
    { id: 99, location: "Amiens", CRS: "AMI" },
    { id: 100, location: "Amington Junction", CRS: "XIM" },
    { id: 101, location: "Amlwch", CRS: "AMW" },
    { id: 102, location: "Ammanford", CRS: "AMF" },
    { id: 103, location: "Ampfield School", CRS: "AMD" },
    { id: 104, location: "Amsterdam Centraal Station", CRS: "AMS" },
    { id: 105, location: "Ancaster", CRS: "ANC" },
    { id: 106, location: "Anderston", CRS: "AND" },
    { id: 107, location: "Andover", CRS: "ADV" },
    { id: 108, location: "Anerley", CRS: "ANZ" },
    { id: 109, location: "Angel LT", CRS: "ZAN" },
    { id: 110, location: "Angel Road", CRS: "AGR" },
    { id: 111, location: "Angerstein Wharf", CRS: "ANW" },
    { id: 112, location: "Angmering", CRS: "ANG" },
    { id: 113, location: "Annan", CRS: "ANN" },
    { id: 114, location: "Anniesland", CRS: "ANL" },
    { id: 115, location: "Ansdell & Fairhaven", CRS: "AFV" },
    { id: 116, location: "Antrim", CRS: "ANM" },
    { id: 117, location: "Apperley Bridge", CRS: "APY" },
    { id: 118, location: "Appleby", CRS: "APP" },
    { id: 119, location: "Appledore (Kent)", CRS: "APD" },
    { id: 120, location: "Appleford", CRS: "APF" },
    { id: 121, location: "Appley Bridge", CRS: "APB" },
    { id: 122, location: "Apsley", CRS: "APS" },
    { id: 123, location: "Arbroath", CRS: "ARB" },
    { id: 124, location: "Archway LT", CRS: "ZAR" },
    { id: 125, location: "Ardgay", CRS: "ARD" },
    { id: 126, location: "Ardingly", CRS: "ARY" },
    { id: 127, location: "Ardlui", CRS: "AUI" },
    { id: 128, location: "Ardrahan (Ireland)", CRS: "XAG" },
    { id: 129, location: "Ardrossan Electric Multiple Unit Sidings", CRS: "XAT" },
    { id: 130, location: "Ardrossan Harbour", CRS: "ADS" },
    { id: 131, location: "Ardrossan South Beach", CRS: "ASB" },
    { id: 132, location: "Ardrossan Town", CRS: "ADN" },
    { id: 133, location: "Ardwick", CRS: "ADK" },
    { id: 134, location: "Ardwick Traction Maintenance Depot", CRS: "XRK" },
    { id: 135, location: "Argyle Street", CRS: "AGS" },
    { id: 136, location: "Arisaig", CRS: "ARG" },
    { id: 137, location: "Arklow", CRS: "ARW" },
    { id: 138, location: "Arlesey", CRS: "ARL" },
    { id: 139, location: "Armadale", CRS: "ARM" },
    { id: 140, location: "Armadale via Mallaig Ship", CRS: "ARA" },
    { id: 141, location: "Armathwaite", CRS: "AWT" },
    { id: 142, location: "Arnhem", CRS: "ARM" },
    { id: 143, location: "Arnos Grove LT", CRS: "ZAG" },
    { id: 144, location: "Arnside", CRS: "ARN" },
    { id: 145, location: "Arram", CRS: "ARR" },
    { id: 146, location: "Arrochar", CRS: "ART" },
    { id: 147, location: "Arsenal LT", CRS: "ZAS" },
    { id: 148, location: "Arundel", CRS: "ARU" },
    { id: 149, location: "Arundel Junction", CRS: "XXA" },
    { id: 150, location: "Arundel London Road", CRS: "ARZ" },
    { id: 151, location: "Ascot", CRS: "ACT" },
    { id: 152, location: "Ascott-under-Wychwood", CRS: "AUW" },
    { id: 153, location: "Ash", CRS: "ASH" },
    { id: 154, location: "Ashburys", CRS: "ABY" },
    { id: 155, location: "Ashchurch", CRS: "ASC" },
    { id: 156, location: "Ashfield", CRS: "ASF" },
    { id: 157, location: "Ashford East Junction", CRS: "XIE" },
    { id: 158, location: "Ashford International", CRS: "ASI" },
    { id: 159, location: "Ashford (Kent)", CRS: "AFK" },
    { id: 160, location: "Ashford PAD", CRS: "ASA" },
    { id: 161, location: "Ashford (Surrey/Middlesex)", CRS: "AFS" },
    { id: 162, location: "Ashford WJ", CRS: "XIW" },
    { id: 163, location: "Ashley", CRS: "ASY" },
    { id: 164, location: "Ashtead", CRS: "AHD" },
    { id: 165, location: "Ashton-under-Lyne", CRS: "AHN" },
    { id: 166, location: "Ashurst", CRS: "AHS" },
    { id: 167, location: "Ashurst New Forest", CRS: "ANF" },
    { id: 168, location: "Ash Vale", CRS: "AHV" },
    { id: 169, location: "Ashwell & Morden", CRS: "AWM" },
    { id: 170, location: "Askam", CRS: "ASK" },
    { id: 171, location: "Aslockton", CRS: "ALK" },
    { id: 172, location: "Aspatria", CRS: "ASP" },
    { id: 173, location: "Aspley Guise", CRS: "APG" },
    { id: 174, location: "Aston", CRS: "AST" },
    { id: 175, location: "Athenry", CRS: "ATR" },
    { id: 176, location: "Atherstone", CRS: "ATH" },
    { id: 177, location: "Atherton", CRS: "ATN" },
    { id: 178, location: "Athlone", CRS: "ATO" },
    { id: 179, location: "Athy", CRS: "ATY" },
    { id: 180, location: "Attadale", CRS: "ATT" },
    { id: 181, location: "Attenborough", CRS: "ATB" },
    { id: 182, location: "Attercliffe", CRS: "ATE" },
    { id: 183, location: "Attercliffe Road", CRS: "ACF" },
    { id: 184, location: "Attleborough", CRS: "ATL" },
    { id: 185, location: "Attymon", CRS: "ATM" },
    { id: 186, location: "Auchinleck", CRS: "AUK" },
    { id: 187, location: "Auchterarder", CRS: "AUC" },
    { id: 188, location: "Audley End", CRS: "AUD" },
    { id: 189, location: "Aughton Park", CRS: "AUG" },
    { id: 190, location: "Avebury Red Lion", CRS: "XAF" },
    { id: 191, location: "Aviemore", CRS: "AVM" },
    { id: 192, location: "Aviemore (Speyside)", CRS: "AVS" },
    { id: 193, location: "Avignon CMT", CRS: "AVI" },
    { id: 194, location: "Avoncliff", CRS: "AVF" },
    { id: 195, location: "Avonmouth", CRS: "AVN" },
    { id: 196, location: "Axminster", CRS: "AXM" },
    { id: 197, location: "Aylesbury", CRS: "AYS" },
    { id: 198, location: "Aylesbury Vale Parkway", CRS: "AVP" },
    { id: 199, location: "Aylesford", CRS: "AYL" },
    { id: 200, location: "Aylesham", CRS: "AYH" },
    { id: 201, location: "Aynho Junction", CRS: "XAN" },
    { id: 202, location: "Ayr", CRS: "AYR" },
    { id: 203, location: "Ayr Carriage Servicing Depot", CRS: "XAR" },
    { id: 204, location: "Ayr Depot", CRS: "XAY" },
    { id: 205, location: "", CRS: "" },
    { id: 206, location: "", CRS: "" },
    { id: 207, location: "", CRS: "" },
    { id: 208, location: "", CRS: "" },
    { id: 209, location: "", CRS: "" },
    { id: 210, location: "", CRS: "" },

   
   





  





  

   

    
    
]

